<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            'USD' => 'Dólar estadounidense',
            'EUR' => 'Euro',
            'PEN' => 'Sol',
            'AFN' => 'Afgani afgano',
            'MGA' => 'Ariary malgache (de Madagascar)',
            'THB' => 'Baht tailandés',
            'PAB' => 'Balboa panameña',
            'ETB' => 'Birr etíope',
            'VEF' => 'Bolívar Fuerte',
            'BOB' => 'Boliviano',
            'GHS' => 'Cedi ghanés',
            'KES' => 'Chelín keniata',
            'SOS' => 'Chelín somalí',
            'TZS' => 'Chelín tanzano',
            'UGX' => 'Chelín ugandés',
            'CRC' => 'Colón costarricense',
            'NIO' => 'Córdoba nicaragüense',
            'DKK' => 'Corona danesa',
            'NOK' => 'Corona noruega',
            'SEK' => 'Corona sueca',
            'GMD' => 'Dalasi gambiano',
            'MKD' => 'Denar macedonio',
            'DZD' => 'Dinar argelino',
            'BHD' => 'Dinar bahreiní',
            'IQD' => 'Dinar iraqí',
            'JOD' => 'Dinar jordano',
            'KWD' => 'Dinar kuwaití',
            'LYD' => 'Dinar libio',
            'RSD' => 'Dinar serbio',
            'TND' => 'Dinar tunecino',
            'AED' => 'Dirham de los Emiratos Árabes Unidos',
            'MAD' => 'Dirham marroquí',
            'STD' => 'Dobra de Santo Tomé y Príncipe',
            'AUD' => 'Dólar australiano',
            'BSD' => 'Dólar bahameño',
            'KYD' => 'Dólar caimano (de Islas Caimán)',
            'CAD' => 'Dólar canadiense',
            'BBD' => 'Dólar de Barbados',
            'BZD' => 'Dólar de Belice',
            'BMD' => 'Dólar de Bermuda',
            'BND' => 'Dólar de Brunei',
            'HKD' => 'Dólar de Hong Kong',
            'SBD' => 'Dólar de las Islas Salomón',
            'SGD' => 'Dólar de Singapur',
            'TTD' => 'Dólar de Trinidad y Tobago',
            'XCD' => 'Dólar del Caribe Oriental',
            'USN' => 'Dólar estadounidense (Siguiente día) (código de fondos)',
            'FJD' => 'Dólar fijiano',
            'GYD' => 'Dólar guyanés',
            'JMD' => 'Dólar jamaicano',
            'LRD' => 'Dólar liberiano',
            'NAD' => 'Dólar namibio',
            'NZD' => 'Dólar neozelandés',
            'SRD' => 'Dólar surinamés (desde el 1 de enero de 2004)',
            'TWD' => 'Dólar taiwanés',
            'ZWL' => 'Dólar zimbabwés',
            'VND' => 'Dong vietnamita',
            'AMD' => 'Dram armenio',
            'SVC' => 'El Salvador Colon',
            'CVE' => 'Escudo caboverdiano',
            'HUF' => 'Forint húngaro',
            'BIF' => 'Franco burundés',
            'KMF' => 'Franco comoriano (de Comoras)',
            'CDF' => 'Franco congoleño',
            'GNF' => 'Franco guineano',
            'RWF' => 'Franco ruandés',
            'CHF' => 'Franco suizo',
            'DJF' => 'Franco yibutiano',
            'HTG' => 'Gourde haitiano',
            'PYG' => 'Guaraní paraguayo',
            'AWG' => 'Guilder de Aruba',
            'ANG' => 'Guilder de las Antillas Holandesas',
            'UAH' => 'Hryvnia ucraniana',
            'PGK' => 'Kina de Papúa Nueva Guinea',
            'LAK' => 'Kip lao',
            'CZK' => 'Koruna checo',
            'ISK' => 'Króna islandesa',
            'HRK' => 'Kuna croata',
            'MWK' => 'Kwacha malawiano',
            'ZMK' => 'Kwacha zambiano',
            'AOA' => 'Kwanza angoleño',
            'MMK' => 'Kyat myanmaro',
            'GEL' => 'Lari georgiano',
            'LVL' => 'Lat letón',
            'ALL' => 'Lek albano',
            'HNL' => 'Lempira hondureña',
            'SLL' => 'Leone de Sierra Leona',
            'MDL' => 'Leu moldavo',
            'RON' => 'Leu rumano',
            'BGN' => 'Lev búlgaro',
            'GIP' => 'Libra de Gibraltar',
            'SHP' => 'Libra de Santa Helena',
            'EGP' => 'Libra egipcia',
            'GBP' => 'Libra esterlina (de Gran Bretaña)',
            'LBP' => 'Libra libanesa',
            'FKP' => 'Libra malvinense',
            'SYP' => 'Libra siria',
            'SDG' => 'Libra sudanesa',
            'SZL' => 'Lilangeni suazi (de Suazilandia)',
            'LTL' => 'Litas lituano',
            'LSL' => 'Loti lesothense (de Lesotho)',
            'AZN' => 'Manat azerbaiyano',
            'BAM' => 'Marco convertible de Bosnia-Herzegovina',
            'MZN' => 'Metical mozambiqueño',
            'NGN' => 'Naira nigeriana',
            'ERN' => 'Nakfa eritreo',
            'BTN' => 'Ngultrum de Bután',
            'TRY' => 'Nueva lira turca',
            'TMT' => 'Nuevo Manat turcomano',
            'ILS' => 'Nuevo shequel israelí',
            'MRO' => 'Ouguiya mauritana',
            'TOP' => 'Pa anga tongano',
            'MOP' => 'Pataca de Macao',
            'ARS' => 'Peso argentino',
            'CLP' => 'Peso chileno',
            'COP' => 'Peso colombiano',
            'CUP' => 'Peso cubano',
            'CUC' => 'Peso cubano Convertible',
            'DOP' => 'Peso dominicano',
            'PHP' => 'Peso filipino',
            'MXN' => 'Peso mexicano',
            'UYU' => 'Peso uruguayo',
            'BWP' => 'Pula de Botswana',
            'GTQ' => 'Quetzal guatemalteco',
            'ZAR' => 'Rand sudafricano',
            'BRL' => 'Real brasileño',
            'IRR' => 'Rial iraní',
            'OMR' => 'Rial omaní (de Omán)',
            'QAR' => 'Rial qatarí',
            'YER' => 'Rial yemení (de Yemen)',
            'KHR' => 'Riel camboyano',
            'MYR' => 'Ringgit malayo',
            'SAR' => 'Riyal saudí',
            'BYR' => 'Rublo bielorruso',
            'RUB' => 'Rublo ruso',
            'TJS' => 'Rublo tayik (de Tayikistán)',
            'MVR' => 'Rufiyaa maldiva',
            'SCR' => 'Rupia de Seychelles',
            'LKR' => 'Rupia de Sri Lanka',
            'INR' => 'Rupia india',
            'MUR' => 'Rupia mauricia',
            'NPR' => 'Rupia nepalesa',
            'PKR' => 'Rupia pakistaní',
            'IDR' => 'Rupiah indonesia',
            'KGS' => 'Som kirguís (de Kirguistán)',
            'UZS' => 'Som uzbeco',
            'BDT' => 'Taka de Bangladesh',
            'WST' => 'Tala samoana',
            'KZT' => 'Tenge kazajo (de Kazajstán)',
            'MNT' => 'Tughrik mongol',
            'USS' => 'United States dollar (Mismo día) (código de fondos)',
            'VUV' => 'Vatu vanuatense',
            'KPW' => 'Won norcoreano',
            'KRW' => 'Won surcoreano',
            'JPY' => 'Yen japonés',
            'CNY' => 'Yuan Renminbi',
            'PLN' => 'Zloty polaco'
        ];

        foreach($currencies as $code => $name) {
            \App\Models\Currency::factory()->create([
                "code" => $code,
                "name" => $name
            ]);
        }
    }
}
